api:
  http_listen: "0.0.0.0:8081"
  prometheus_http_listen: ":9102"
  grpc_listen: "0.0.0.0:5300"
  prometheus_grpc_listen: ":9103"

scheduler:
  check_in_seconds: 10
  notify_in_seconds: 3600

sender:
  num_of_senders: 5
  prometheus_listen: ":9104"

postgres:
  host_port: "postgres:5432"
  user: "postgres"
  pass: "postgres"
  database: "calendar"
  timeout_connect: 5
  timeout_execute: 10

log:
  file: "logs/log.txt"
  level: "debug"

rmq:
  host_port: "rabbitmq:5672"
  timeout_connect: 10
  user: "guest"
  pass: "guest"
  queue: "scheduler"