http_listen: "0.0.0.0:8081"
grpc_listen: "0.0.0.0:5300"
log_file: "logs/log.txt"
log_level: "debug"
db_host_port: "192.168.23.2:5432"
db_user: "postgres"
db_pass: "postgres"
db_database: "calendar"
db_timeout_connect: 5
db_timeout_execute: 10

